name = "Deitheme"
license = "MIT"
licenselink = "https://github.com/deicoon/deitheme/blob/master/LICENSE.md"
description = "Deicoon's official and original theme."
homepage = "http://deicoon.com/products/deitheme"
tags = ["disqus", "google analytics", "responsive", "syntax highlighting", "l10n"]
features = []
min_version = "0.31.1"

[author]
  name = "Perceval Faramaz"
  homepage = "http://perceval.faramaz.com"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
